void main() {
  
  try{
    int valor=0;
    int nome = 2;

    print(valor/nome);
  }
  catch(erro){
    
    print("Houve este erro: \n\n\n\n $erro");
    
  }
  finally{
    print("Feito!");
  }

}
